# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Math-Taylor
version:      1.00
version_from: lib/Math/Taylor.pm
installdirs:  site
requires:
    Math::Symbolic:                0.128
    Test::More:                    0
    Test::Pod::Coverage:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
